[project]
name = "generator"
version = "0.1.0"
description = "Balloon Game Data Generator"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "aiokafka>=0.12.0",
  "pydantic>=2.10.6",
  "python-dotenv>=1.0.1",
]
