---
# Check LocalStack namespace
- name: Wait for LocalStack namespace to be active
  kubernetes.core.k8s_info:
    kind: Namespace
    name: "{{ localstack_namespace | default('localstack') }}"
    api_version: v1
  register: localstack_ns_status
  until: localstack_ns_status.resources[0].status.phase is defined and localstack_ns_status.resources[0].status.phase ==
    "Active"
  retries: 30
  delay: 10
  tags:
    - namespace
    - localstack

# Check LocalStack deployment
- name: Wait for LocalStack deployment to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    name: localstack
    namespace: "{{ localstack_namespace | default('localstack') }}"
    api_version: apps/v1
  register: localstack_status
  until: >
    localstack_status.resources[0].status.availableReplicas is defined and
    localstack_status.resources[0].status.availableReplicas > 0 and localstack_status.resources[0].status.readyReplicas
    is defined and localstack_status.resources[0].status.readyReplicas == localstack_status.resources[0].status.replicas
  retries: 60
  delay: 10
  tags:
    - deployment
    - localstack
