# https://taskfile.dev

version: "3"

vars:
  IMAGE_REGISTRY: k3d-registry.localhost:5001
  IMAGE_NAME: balloon-pop-generator

tasks:
  build-generator:
    dir: generator
    desc: build the generator image and push to local registry
    cmds:
      - >-
        docker build --no-cache --push -t {{.IMAGE_REGISTRY}}/{{.IMAGE_NAME}} .
    silent: false

  default:
    cmds:
      - task: build-generator

  generator-stop:
    silent: true
    desc:  scale down the generator pod
    cmds:
      - >-
        kubectl scale deployment -n default balloon-game-data-generator --replicas 0

  generator-start:
    silent: true
    desc: scale up the generator pod
    cmds:
      - >-
        kubectl scale deployment -n default balloon-game-data-generator --replicas 1

  generator-restart:
    silent: true
    cmds:
      - task: generator-stop
      - sleep .3
      - task: generator-start

  dashboard-local:
    silent: true
    desc: run the streamlit dashboard locally
    cmds:
      - uv run --package=dashboard dashboard

  generator-local:
    silent: true
    desc: run the data generator  locally
    aliases:
      - dashboard
      - streamlit
    cmds:
      - uv run --package=generator generator

  create-test-topic:
    silent: false
    cmds:
      - >-
        cat <<EOF | kubectl apply -f - 
          apiVersion: kafka.strimzi.io/v1beta2
          kind: KafkaTopic 
          metadata:
            labels:
              strimzi.io/cluster: my-cluster
            name: test
            namespace: kafka
        spec:
          config:
            retention.ms: 7200000
            segment.bytes: 1073741824
          partitions: 1
          replicas: 1
        EOF
