apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: ${K3D_CLUSTER_NAME}
servers: 1
agents: 1
image: "rancher/k3s:${K3S_VERSION}"
ports:
  # Kafka External 9094(external) set to nodeport 31905 and it will be accessible from host using 19094
  - port: 19094:31905
    nodeFilters:
      - loadbalancer
  # Kafka External 31906 broker address which is accessible using 19095 form host
  - port: 19095:31906
    nodeFilters:
      - loadbalancer
  # RisingWave SQL - 4567 set to nodeport 31910 and it will be accessible from host using 14566
  - port: 14567:31910
    nodeFilters:
      - loadbalancer
  # Localstack - 4566 set to nodeport 31566 and it will be accessible from host using 4566
  - port: 4566:31566
    nodeFilters:
      - loadbalancer
  # REST Catalog - polaris 18181 set to port 32181 and it will be accessible via 8181
  - port: 18181:32181
    nodeFilters:
      - loadbalancer

registries: # define how registries should be created or used
  create: # creates a default registry to be used with the cluster; same as `--registry-create registry.localhost`
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5001"

volumes:
  # Deploy Kafka
  - volume: ${FEATURES_DIR}/features/strimzi-kafka-op.yaml:/var/lib/rancher/k3s/server/manifests/strimzi-kafka-op.yaml
    nodeFilters:
      - server:*

  # Deploy PostgreSQL
  - volume: ${FEATURES_DIR}/features/postgresql.yaml:/var/lib/rancher/k3s/server/manifests/postgresql.yaml
    nodeFilters:
      - server:*

  # Deploy RisingWave
  - volume: ${FEATURES_DIR}/features/risingwave.yaml:/var/lib/rancher/k3s/server/manifests/risingwave.yaml
    nodeFilters:
      - server:*

  # Deploy Localstack
  - volume: ${FEATURES_DIR}/features/localstack.yaml:/var/lib/rancher/k3s/server/manifests/localstack.yaml
    nodeFilters:
      - server:*
files:
  - description: Deploy Kafka Cluster and related resources - topics, KRraft nodes etc.,
    source: ../k8s/features/kafka-cluster.yaml
    destination: /var/lib/rancher/k3s/server/manifests/kafka-cluster.yaml
