#!ansible-playbook
---
- name: Ensure the cluster is ready with required deployments
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - defaults/main.yml

  pre_tasks:
    - name: Install required collections
      ansible.builtin.command: ansible-galaxy collection install kubernetes.core
      changed_when: false
  tasks:
    - name: Localstack Status Checks
      ansible.builtin.include_tasks:
        file: tasks/localstack_checks.yml
      tags:
        - localstack

    - name: Risingwave Status Checks
      ansible.builtin.include_tasks:
        file: tasks/risingwave_checks.yml
      tags:
        - risingwave

    - name: Kafka Status Checks
      ansible.builtin.include_tasks:
        file: tasks/kafka_checks.yml
      tags:
        - kafka

    - name: Polaris Status Checks
      ansible.builtin.include_tasks:
        file: tasks/polaris_checks.yml
      tags:
        - polaris
