name: Site

on:
  push:
    branches:
      - "main"
env:
  SITE_DIR: "site"
permissions:
  contents: write
jobs:
  buildAnDeploySite:
    name: "Build site with mkdocs"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "mkdocs>=1.6.1,<=2.0.0" "mkdocs-material>=9.5.44,<10.0.0"
      - name: Build Site
        run: |
          mkdocs build
      - name: Deploy Site
        id: deploy_site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "${{ env.SITE_DIR }}"
          publish_branch: "gh-pages"
          full_commit_message: "[Release]${{ github.event.head_commit.message }}"
